# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
def import_pods
    pod 'Gifu'
    pod 'GooglePlaces'
    pod 'Alamofire', '~> 3.4.1'
    pod 'SwiftyJSON', '~> 2.4.0'
    pod 'RealmSwift'
    pod 'Kingfisher', '~> 2.6.1'
end
target 'Weather' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

# Pods for Weather
import_pods

end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3' # or '3.0'
        end
    end
end